# Permalinks
#
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title: simple_quandaries
tagline: 'Open and wholly receptive'
description: 'Ramblings of a software engineer, also human...labels are elusive.'
url: https://brandon-powers.github.io
baseurl: https://brandon-powers.github.io

# About/contact
author:
  name: Brandon Powers
  url: https://twitter.com/bk_powers

# Custom vars
version: 1.0.0
