# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               bran-crumbs 
tagline:             'Breathe'
description:         'Crumbs from the man himself, Bran'
url:                 https://brandon-powers.github.io
paginate:            5

# About/contact
author:
  name:              Brandon Powers
  url:               https://twitter.com/bk_powers

# Custom vars
version:             1.0.0
